import React from 'react'
import Layout from './layout'
import ProcedureLayout from '../procedure/layout'

const CB = () => {
  return (
    <div className='flex flex-col items-start gap-4'>
      <Layout
      definition='A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world'
      purpose='A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world'
      procedure={
      <ProcedureLayout
      desc='A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world'
      equipment={
        <>
          
          <p>A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world</p>
          <p>A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world</p>
        </>
      }
      circuit={
        <>
           <p>A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world</p>
           <p>A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world</p>
        </>
      }

      />}
      criteria='A current transformer is a type of transformer that is used to measure alternating current (AC). It produces a current in its secondary which is proportional to the current in its primary. Current transformers, along with voltage or potential transformers, are instrument transformers. Instrument transformers scale the large values of voltage or current to small, standardized values that are easy to handle for instruments and protective relays. The current transformer presents a negligible load to the primary circuit. Current transformers are commonly used in metering and protective relays in the electrical power industry. They are designed to provide a current in its secondary coil proportional to the current flowing in its primary. Current transformers are used extensively for measuring current and monitoring the operation of the power grid. Along with voltage leads, revenue-grade current transformers drive the electrical utilitys watt-hour meter on virtually every commercial and industrial installation in the world' />
    </div>
  )
}

export default CB