export const widths = [
  "44px",
  "44px",
  "190px",
  "100px",
  "115px",
  "115px",
  "180px",
  "110px",
  "90px",
  "45px",
  "45px",
  "45px",
  "45px",
  "70px",
];
export const Document = [
  [
    "1",
    "1.1",
    "Approved final revision Document from Contractor",
    "Documents Review",
    "IFC Drawings / Project",
    "Before work and revisions",
    "Project Requirements / Concept Drawings",
    "Shop drawings",
    "Approved Document",
    "H",
    "w",
    "w",
    "R",
    "",
  ],
  [
    "",
    "1.2",
    "Approval of Method Statement",
    "Documents Review",
    "Project / Specifications",
    "Before work and revisions",
    "Approved Procedure / Project Specs",
    "Project Specs",
    "Approved Document",
    "H",
    "w",
    "w",
    "R",
    "",
  ],
];

export const Accept = [
    [
      "3",
      "3.1",
      "Final acceptance <br /> of work done",
      "Visual inspection",
      "Factory test report",
      "Each item",
      "Factory test report/ Rated nameplate data/ MOS/",
      "vendor manual",
      "Test report",
      "H",
      "R",
      "R",
      "R",
      "",
    ],
  ];
