export const Abb: { [key: string]: string } = {
  "IR": 'Insulation Resistance',
  "WR": 'Winding Insulation Resistance',
  "WR-T": 'Polarization Index',
  "PI": 'Winding Resistance (all taps)',
  "EI": 'Excitation Current',
  "PF": 'nsulation Power Factor',
  "VR": 'Vector Relationship',
  "WTI": 'Winding Temperature Indicator',
  "OTI": 'Oil Temperature Indicator',
  "SC": 'Short Circuit',
  "TR": 'Turn Ratio',
  "IO": 'Insulating Oil',
  "MB": 'Magnetic Balance',
  "EIR": 'Core Earthing\nInsulation Resistance',
  "MI": 'Magnetizing current',
  "F": 'Cooling Fans',
  "MCB": 'MCBs & Thermal Overloads',
  "ZSI": 'Zero sequence impedance',
  "COTS": 'Calibration of Oil\nand Winding Temp. Sensors',
  "FC": 'Supervision Equipment Functional Checks',
  "ODS": 'Oil Dielectric Strength',
  "OLTC": 'ON-Load Tap Changer Functional',
  "DGA": 'Dissolved Gas Analysis',
  "SFRA": 'Sweep Frequency response Analysis (SFRA)',
  "BPF": 'Bushing Power Factor',
  "CWIR": 'Sweep Frequency response Analysis (SFRA)',
  "AVR & E": 'AVR and Earthing',
  "ACB": 'Air Circuit Breaker',
  "Relay": 'Relay',
  "CT": 'Current Transformer',
  "PT": 'Potentional Transformer',
  "K": 'Aux. Contactor',
  "VLF": 'High Potentional',
  "PD": 'Parital Discharge',
  "TD": 'Tan Delta',
  "TRAFO": 'Transformer',
  "SWGR": 'Switchgear',
  "CABLE": 'Cable',
  "RMU": 'RMU',
  "CB": 'Circuit Breaker',
  'SPRING': 'Spring Charge',
  "IT": 'Impedance Test',
  "DSV": 'Distance Setting Verification',
  "DPC": 'Directional Power Calibration',
  "DET": 'Directional Element Testing',
  "USV": 'Undercurrent Setting Verification',
  "OT": 'Operational Test',
  "PSV": 'Phase Sequence Verification',
  "VAT": 'Voltage Asymmetry Test',
  "OSV": 'Overcurrent Setting Verification',
  "IPT": 'Instantaneous Pickup Test',
  "TOSV": 'Time Overcurrent Setting Verification',
  "TDC": 'Time Dial Calibration',
  "CBCT": 'CB Control Testing',
  "CBTT": 'CB Tripping Test',
  "DOSV": 'Directional Overcurrent Setting Verification',
  "PACC": 'Phase Angle Comparator Calibration',
  "PDM": 'Phase Difference Measurement',
  "AFT": 'Autoreclose Function Test',
  "RTV": 'Reclosing Time Verification',
  "CPRT": 'Carrier/Pilot-Wire Receiver Test',
  "CSC": 'Communication System Check',
  "DRT": 'Differential Testing',
  "DPCAL": 'Differential Protection Calibration',
  "LSFT": 'Line Switch Function Test',
  "SPE": 'Switching Performance Evaluation',
  "VRC": 'Voltage Regulator Calibration',
  "VSA": 'Voltage Stability Assessment',
  "VDSV": 'Voltage Directional Setting Verification',
  "VPDC": 'Voltage and Power Directional Calibration',
  "BC": 'Binary Check',
  "MC": 'Meter Check',
  "TT": 'Trip Test',
  "CONF": 'Configuration',
  "SV": 'Setting Verification',
  "VHR": 'Volts per Hertz',
  "UVR": 'Undervoltage',
  "LFR": 'Loss of Field',
  "RPR": 'Reverse Power',
  "TOR": 'Thermal Overload',
  "PFR": 'Power Factor',
  "OVR": 'Overvoltage',
  "VBR": 'Voltage Balance',
  "GDR": 'Ground Detector',
  "DOR": 'Directional Overcurrent',
  "FR": 'Frequency',
  "LOR": 'Lockout',
  "TSR": 'Tripping or Trip Circuit Supervision',
  "SS": 'Supervisory Switch',
  "DCD": 'Discrete Control Device',
  "21": 'Distance',
  "24": 'Volts per Hertz',
  "27": 'Undervoltage',
  "32": 'Directional Power',
  "37": 'Undercurrent',
  "40": 'Loss of Field',
  "46": 'Reverse Power',
  "47": 'Phase Sequence Voltage',
  "49": 'Thermal Overload',
  "50": 'Instantaneous Overcurrent',
  "51": 'Time Overcurrent',
  "52": 'Circuit Breaker (CB) Control',
  "55": 'Power Factor',
  "59": 'Overvoltage',
  "60": 'Voltage Balance',
  "63": 'Pressure Switch',
  "64": 'Ground Detector',
  "67": 'Directional Overcurrent',
  "78": 'Phase Angle Comparator',
  "79": 'Autoreclose',
  "81": 'Frequency',
  "85": 'Carrier or Pilot-Wire Receiver',
  "86": 'Lockout',
  "87": 'Differential Protection',
  "89": 'Line Switch',
  "90": 'Voltage Regulator',
  "91": 'Voltage Directional',
  "92": 'Voltage and Power Directional',
  "94": 'Tripping or Trip Circuit Supervision',
  "95": 'Supervisory Switch',
  "98": 'Discrete Control Device',
  "99": 'Retransmission',
  // switchgear
  "DW": 'Disconnect Switch',
  "DM": 'Digital Meter',
  // circuit breaker
  "TIMING": 'Timing',
  'HIPOT': 'Hipot',
  'PICK': 'Pickup',
  'CRM': 'Contact Resistance',
  'SI': 'Sec Injection',
  // transformer
  "CORE": 'Core and winding',
  "INSULATION": 'Insulation system',
  "COOL": 'Cooling system',
  "TAP": 'Tap changer',
  "BUSH": 'Bushing and Insulation',
  "FUNCTION": 'Functionality',
  "WRT": 'Winding Resistance',
  
  "Z": 'Impedance',
  
  "OC": 'Open-Circuit',
 
  "DS": 'Dielectric Strength',
  "T": 'Temperature Rise',
  "CG": 'Core Grounding',
  "PFD/FD": 'Power Factor/Dissipation Factor',
  
  "MOISTURE": 'Moisture Content',
  "FA": 'Furan Analysis',
  "IPF": 'Insulation Power Factor',
  "OQ": 'Oil Quality',
  "OL": 'Oil Level',
  
  "OF": 'Oil Flow',
  "CF": 'Cooling Fan',
  "RHE": 'Radiator/Heat Exchanger',
  "BR": 'Buchholz',
  "PRD": 'Pressure Relief Device',
  "TC": 'Tap Changer',
  "TI": 'Tap Changer Insulation Resistance',
  "TCET": 'Tap Changer Electrical Continuity',
  "TOLT": 'Tap Changer Oil Leak',
  "BIR": 'Bushing Insulation Resistance',
 

  "BOL": 'Bushing Oil Level',

  "SA": 'Surge Arrester',
  "GS": 'Grounding System',
  "NV": 'Nameplate Verification',

  "E": 'Efficiency',
  "LL": 'Load Loss',
  "NLL": 'No-Load Loss',

  "STWC": 'Short-Time Withstand Current',
  "LIVW": 'Lightning Impulse Voltage Withstand',
  "PFVW": 'Power Frequency Voltage Withstand'
};

