export const atom = [
    'button', 
    'input', 
    'checkbox', 
    'radio', 
    'toggle', 
    // 'slider', 
    // 'progress', 
    'icon', 
    // 'avatar', 
    // 'badge', 
    // 'label', 
    // 'tooltip', 
    // 'popover', 
    // 'divider', 
    'loader', 
    'spinner', 
    // 'stepper', 
    // 'chip', 
    // 'tag', 
    // 'menu', 
    'link', 
    'typography'
  ];
  
  export const compound = [
    'form', 
    'dropdown', 
    'autocomplete', 
    'calendar', 
    'datepicker', 
    'timepicker', 
    'colorpicker', 
    'uploader', 
    'selector', 
    'card', 
    'list', 
    'grid', 
    'tabs', 
    'accordion', 
    'pagination', 
    'table', 
    'tooltip', 
    'popover', 
    'modal', 
    'notification', 
    'toolbar', 
    'wizard'
  ];
  
  export const cell = [
    'dashboard', 
    'feed', 
    'notification', 
    'chat', 
    'searchbar', 
    'breadcrumb', 
    'profile', 
    'tasklist', 
    'calendar', 
    'timeline', 
    'project', 
    'userprofile', 
    'settings', 
    'analytics', 
    'help', 
    'feedback', 
    'error'
  ];
  
  export const organ = [
    'workflow', 
    'integration', 
    'reporting', 
    'usermanagement', 
    'rolemanagement', 
    'access', 
    'audit', 
    'settings', 
    'theme', 
    'plugin', 
    'data', 
    'api', 
    'billing', 
    'collaboration', 
    'knowledge', 
    'onboarding', 
    'export'
  ];