
export const kit = [
  {
    src: "/kit/b10e.png",
    alt: "B10E",
    width: 130,
    id: 123415457489 ,
    bg: "#C0C2C8",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "Available",
    under: "Store",
    location: "",
    price: "",
  },
  {
    src: "/kit/ct.png",
    alt: "CT Analyzer",
    width: 140,
    id: 1234,
    bg: "#047FC6",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "Available",
    under: "Store",
    location: "",
    price: "",
  },
  {
    src: "/kit/delta4000.png",
    alt: "Delta4000",
    width: 100,
    id: 1234,
    bg: "#6A787A",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "Store",
    location: "",
    price: "",
  },
  {
    src: "/kit/dlro600.png",
    alt: "DLRO600",
    width: 140,
    id: 1234,
    bg: "#EBEDEC",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/egil.png",
    alt: "Egil",
    width: 145,
    id: 1234,
    bg: "#E1E0D0",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/frax101.png",
    alt: "Frax101",
    width: 150,
    id: 1234,
    bg: "#CFD3D5",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/freja300.png",
    alt: "Freja300",
    width: 150,
    id: 1234,
    bg: "#ECE8DF",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/hipot.png",
    alt: "HiPot",
    width: 70,
    id: 1234,
    bg: "#CCCCCC",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/hva60.png",
    alt: "HVA60",
    width: 95,
    id: 1234,
    bg: "#C4C7CC",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/lcr55a.png",
    alt: "LCR55A",
    width: 145,
    id: 1234,
    bg: "#F04849",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/mcf750.png",
    alt: "MCF750",
    width: 140,
    id: 1234,
    bg: "#D4DAD1",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/mit300.png",
    alt: "MIT300",
    width: 145,
    id: 1234,
    bg: "#DBDDDF",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/mit520.png",
    alt: "MIT520",
    width: 145,
    id: 1234,
    bg: "#C5C9BA",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/mit525.png",
    alt: "MIT525",
    width: 120,
    id: 1234,
    bg: "#CACBC7",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/mom600a.png",
    alt: "MOM600A",
    width: 150,
    id: 1234,
    bg: "#D3D7DA",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/oden.png",
    alt: "Oden",
    width: 85,
    id: 1234,
    bg: "#CAC6BD",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/ots80pd.png",
    alt: "OTS80PD",
    width: 110,
    id: 1234,
    bg: "#FCF8ED",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/pdtd60.png",
    alt: "PDTD60",
    width: 90,
    id: 1234,
    bg: "#C9CCCE",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/sverker750.png",
    alt: "Sverker750",
    width: 120,
    id: 1234,
    bg: "#BAAC9D",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
  {
    src: "/kit/ttr330.png",
    alt: "TTR330",
    width: 140,
    id: 1234,
    bg: "#B8B5BA",
    calibration: "",
    datasheet: "",
    manual: "",
    status: "",
    under: "",
    location: "",
    price: "",
  },
];

export const docs = [
  { icon: 'ph:engine-thin', label: 'Status' },
  { icon: 'arcticons:permissionsmanager', label: 'calib.' },
  { icon: 'arcticons:google-docs', label: 'Datash.' },
  { icon: 'arcticons:user-manual', label: 'user ' },,
  { icon: 'arcticons:pdf-file', label: 'service' },
  { icon: 'ph:mouse-thin', label: 'software' },
  { icon: 'ph:camera-thin', label: 'photo' }
]