export const cardsData = [
  {
    name: "قاسم الظافر",
    image: "/author/gasm.png",
    rank: "الامين العام",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "gm@nmbd.org",
    dail: "0917150001",
  },
  {
    name: "هشام احمد",
    image: "/author/hesham.png",
    rank: "الامين السياسي",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "hm@nmbd.org",
    dail: "0917150001",
  },
  {
    name: "المقداد الهجان",
    image: "/author/almgdad.png",
    rank: "الامين الثقافي",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "gm@nmbd.org",
    dail: "0917150001",
  },
  {
    name: "ابو بكر جيكوني ",
    image: "/author/abobakr.png",
    rank: "الامين الاعلامي",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "gm@nmbd.org",
    dail: "0917150001",
  },
];
