export type Paper = {
    title: string;
    desc: string;
  };
  
  export type Project = {
    src: string;
    name: string;
    papers: Paper[];
  };
  
  export const projects: Project[] = [
    {
      src: "/project/raksha.png",
      name: "Raksha",
      papers: [
        { title: "Raksha", desc: "Revolutionizing personal safety" },
        { title: "Inspire", desc: "Advanced safety features" },
        { title: "Contributors", desc: "50" },
        { title: "Sponsor", desc: "10" },
        { title: "Investor", desc: "20,000 Dinars" },
        { title: "stack", desc: "30 Dinars" },
      ],
    },
    {
      src: "/project/plane.png",
      name: "Frnas",
      papers: [
        { title: "Frnas", desc: "Drone for the delivery of first aid" },
        { title: "Inspire", desc: "MQ-9" },
        { title: "Contributors", desc: "42" },
        { title: "CEO", desc: "Mohamed Norian" },
        { title: "Sponsor", desc: "7" },
        { title: "Investor", desc: "10,000 Dinars" },
        { title: "stack", desc: "28 Dinars" },
      ],
    },
    {
      src: "/project/sun.png",
      name: "Solar",
      papers: [
        { title: "Solar", desc: "Harnessing the power of the sun" },
        { title: "Inspire", desc: "Innovative solar solutions" },
        { title: "Contributors", desc: "35" },
        { title: "Sponsor", desc: "8" },
        { title: "Investor", desc: "15,000 Dinars" },
        { title: "stack", desc: "25 Dinars" },
      ],
    },
    {
      src: "/project/office.png",
      name: "Maktb",
      papers: [
        { title: "Maktb", desc: "Reimagining the workspace" },
        { title: "Inspire", desc: "Modern office designs" },
        { title: "Contributors", desc: "60" },
        { title: "Sponsor", desc: "12" },
        { title: "Investor", desc: "25,000 Dinars" },
        { title: "stack", desc: "40 Dinars" },
      ],
    },
    {
      src: "/project/alkhwarizmi.png",
      name: "Alkhwarizmi",
      papers: [
        { title: "Alkhwarizmi", desc: "Innovative AI solutions" },
        { title: "Inspire", desc: "Cutting-edge technology" },
        { title: "Contributors", desc: "28" },
        { title: "Sponsor", desc: "6" },
        { title: "Investor", desc: "12,000 Dinars" },
        { title: "stack", desc: "22 Dinars" },
      ],
    },
    {
      src: "/project/jena.png",
      name: "Jena",
      papers: [
        { title: "Jena", desc: "Eco-friendly products" },
        { title: "Inspire", desc: "Sustainable living" },
        { title: "Contributors", desc: "45" },
        { title: "Sponsor", desc: "9" },
        { title: "Investor", desc: "18,000 Dinars" },
        { title: "stack", desc: "35 Dinars" },
      ],
    },
    {
      src: "/project/favicon.ico",
      name: "Databayt",
      papers: [
        { title: "Databayt", desc: "Data-driven solutions" },
        { title: "Inspire", desc: "Big data analytics" },
        { title: "Contributors", desc: "55" },
        { title: "Sponsor", desc: "11" },
        { title: "Investor", desc: "22,000 Dinars" },
        { title: "stack", desc: "38 Dinars" },
      ],
    },
    {
      src: "/project/hertz.png",
      name: "Hertz",
      papers: [
        { title: "Hertz", desc: "Innovative sound technology" },
        { title: "Inspire", desc: "High-fidelity audio" },
        { title: "Contributors", desc: "32" },
        { title: "Sponsor", desc: "7" },
        { title: "Investor", desc: "14,000 Dinars" },
        { title: "stack", desc: "26 Dinars" },
      ],
    },
    {
      src: "/project/biogas.png",
      name: "Biogas",
      papers: [
        { title: "Biogas", desc: "Clean energy solutions" },
        { title: "Inspire", desc: "Sustainable fuel" },
        { title: "Contributors", desc: "40" },
        { title: "Sponsor", desc: "8" },
        { title: "Investor", desc: "16,000 Dinars" },
        { title: "stack", desc: "28 Dinars" },
      ],
    },
    {
      src: "/project/polymer.png",
      name: "Polymer",
      papers: [
        { title: "Polymer", desc: "Advanced material science" },
        { title: "Inspire", desc: "High-performance materials" },
        { title: "Contributors", desc: "37" },
        { title: "Sponsor", desc: "7" },
        { title: "Investor", desc: "13,000 Dinars" },
        { title: "stack", desc: "24 Dinars" },
      ],
    },
    {
      src: "/project/alshifaa.png",
      name: "Alshifaa",
      papers: [
        { title: "Alshifaa", desc: "Innovative healthcare" },
        { title: "Inspire", desc: "Medical advancements" },
        { title: "Contributors", desc: "58" },
        { title: "Sponsor", desc: "10" },
        { title: "Investor", desc: "21,000 Dinars" },
        { title: "stack", desc: "34 Dinars" },
      ],
    },
    {
      src: "/project/post.png",
      name: "Post",
      papers: [
        { title: "Post", desc: "Modern postal solutions" },
        { title: "Inspire", desc: "Efficient delivery systems" },
        { title: "Contributors", desc: "44" },
        { title: "Sponsor", desc: "9" },
        { title: "Investor", desc: "17,000 Dinars" },
        { title: "stack", desc: "29 Dinars" },
      ],
    },
    {
      src: "/project/mujadad.png",
      name: "Mujadad",
      papers: [
        { title: "Mujadad", desc: "Reconditioning solutions" },
        { title: "Inspire", desc: "Green energy" },
        { title: "Contributors", desc: "36" },
        { title: "Sponsor", desc: "8" },
        { title: "Investor", desc: "15,000 Dinars" },
        { title: "stack", desc: "27 Dinars" },
      ],
    },
    {
      src: "/project/auto.png",
      name: "Auto",
      papers: [
        { title: "Auto", desc: "Automotive workshop" },
        { title: "Inspire", desc: "Smart vehicles" },
        { title: "Contributors", desc: "50" },
        { title: "Sponsor", desc: "10" },
        { title: "Investor", desc: "20,000 Dinars" },
        { title: "stack", desc: "30 Dinars" },
      ],
    },
    {
      src: "/project/hamari.png",
      name: "Hamari",
      papers: [
        { title: "Hamari", desc: "Agricultural advancements" },
        { title: "Inspire", desc: "Smart farming" },
        { title: "Contributors", desc: "42" },
        { title: "Sponsor", desc: "9" },
        { title: "Investor", desc: "18,000 Dinars" },
        { title: "stack", desc: "28 Dinars" },
      ],
    },
    {
      src: "/project/hook.png",
      name: "Najil",
      papers: [
        { title: "Najil", desc: "Fishing technology" },
        { title: "Inspire", desc: "Sustainable fishing" },
        { title: "Contributors", desc: "34" },
        { title: "Sponsor", desc: "7" },
        { title: "Investor", desc: "14,000 Dinars" },
        { title: "stack", desc: "23 Dinars" },
      ],
    },
 
     {
    src: "/project/book.png",
    name: "Bookstore",
    papers: [
      { title: "Bookstore", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/dahab.png",
    name: "Dahab",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/bullet.png",
    name: "Bullet",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/mandeel.png",
    name: "Mendeal",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/lotion.png",
    name: "Lotion",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/leather.png",
    name: "Leather",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/tv.png",
    name: "Screen",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/souq.png",
    name: "Souq",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/riche.png",
    name: "Riche",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/seed.png",
    name: "Seed",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/peanut.png",
    name: "Peanut",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/tomato.png",
    name: "Salsa",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/semsem.png",
    name: "Semsem",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/outdoor.png",
    name: "Outdoor",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/basketball.png",
    name: "Basketball",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/volleyball.png",
    name: "Volleyball",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/soccer.png",
    name: "Soccer",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/swim.png",
    name: "Swim",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/tennis.png",
    name: "Tennis",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/snow.png",
    name: "Snow",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/alyamama.png",
    name: "Alyamama",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/smart.png",
    name: "Smart",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/speaker.png",
    name: "Acoustic",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/real-estate.png",
    name: "Estate",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/school.png",
    name: "Madrsa",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/mosque.png",
    name: "Masjid",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/visba.png",
    name: "Visba",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/zabadi.png",
    name: "Zabadi",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
  {
    src: "/project/scissor.png",
    name: "Scissor",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "stack", desc: "28 Dinars" },
    ],
  },
];
